### ISSUE TITLE
Cannot find dependency for Observable.interval in schema.py

### ISSUE THREAD

**Issue by miketout** [IlyaRadinsky/tornadoql#1]
Hi Ilya,
Nice work on graphene/Tornado/subscriptions integration! I'm looking to leverage it for a project, and I'm wondering what the "Observable.interval" refers to. I'm not seeing it in rx. My apologies if I'm missing something obvious. Thanks!

**Comment by miketout** [comment]
Never mind. It seems that it is in unused code of resolve_randomInt(). Thanks.

**Comment by IlyaRadinsky** [comment]
Hi, no problem!
