### ISSUE TITLE
Converted into a generalized package TornadoQL

### ISSUE THREAD

**Issue by miketout** [IlyaRadinsky/tornadoql#2]
I thought I'd mention that I repackaged your boilerplate and created a setup.py, so it can be easily installed and integrated into other projects in a more general way. Let me know if you'd like these changes.
[https://github.com/miketout/tornado-graphql-server](https://github.com/miketout/tornado-graphql-server)

**Comment by IlyaRadinsky** [comment]
Yes, sure, it would be great!
